"""E.1 单测：C3 FeedbackBundle schema。"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest
from pydantic import ValidationError

from factor_lab.feedback.schema import (
    ActiveFactorSummary,
    FailedCandidateSummary,
    FeedbackBundle,
    RetiredFactorSummary,
)


def _ts(y: int = 2026, m: int = 4, d: int = 20) -> datetime:
    return datetime(y, m, d, 0, 0, 0, tzinfo=timezone.utc)


def _active(name: str = "QualPersist_60D") -> ActiveFactorSummary:
    return ActiveFactorSummary(
        factor_id=f"manual_{name}_abcdef0123",
        name=name,
        family="quality_persist",
        parquet_version=1,
        tags=("production", "legacy"),
    )


def _retired(name: str = "VolRet_5D") -> RetiredFactorSummary:
    return RetiredFactorSummary(
        factor_id=f"manual_{name}_11d70180fb",
        name=name,
        family="volume_price_reversal",
        retired_at=_ts(2026, 4, 10),
        reason="oracle default FAIL: rank_ic=0.006, ic_ir=0.024",
    )


def _failed(name: str = "VolRev_10D", cycle_id: str = "cycle-A") -> FailedCandidateSummary:
    return FailedCandidateSummary(
        name=name,
        family="volume_price_reversal",
        cycle_id=cycle_id,
        stage="default",
        decision="FAIL",
        failure_modes=("ic", "orthogonality"),
        metrics={"rank_ic": 0.004, "max_abs_corr": 0.72},
    )


# ---------------------------------------------------------------------- schema


def test_active_factor_summary_roundtrip() -> None:
    af = _active()
    data = af.model_dump()
    af2 = ActiveFactorSummary.model_validate(data)
    assert af == af2
    assert af.family == "quality_persist"


def test_active_factor_rejects_bad_factor_id() -> None:
    with pytest.raises(ValidationError):
        ActiveFactorSummary(
            factor_id="notmatching",
            name="X",
            parquet_version=1,
        )


def test_retired_factor_requires_reason() -> None:
    with pytest.raises(ValidationError):
        RetiredFactorSummary(
            factor_id="manual_X_abcdef0123",
            name="X",
            retired_at=_ts(),
            reason="",
        )


def test_failed_candidate_rejects_pass_decision() -> None:
    with pytest.raises(ValidationError):
        FailedCandidateSummary(
            name="X",
            cycle_id="cycle-A",
            stage="default",
            decision="PASS",  # PASS 不允许进 recent_fails
            failure_modes=("ic",),
            metrics={},
        )


def test_failed_candidate_rejects_unknown_failure_mode() -> None:
    with pytest.raises(ValidationError):
        FailedCandidateSummary(
            name="X",
            cycle_id="cycle-A",
            stage="default",
            decision="FAIL",
            failure_modes=("not_a_real_check",),
            metrics={},
        )


def test_failed_candidate_dedups_failure_modes() -> None:
    ff = FailedCandidateSummary(
        name="X",
        cycle_id="cycle-A",
        stage="default",
        decision="FAIL",
        failure_modes=("ic", "orthogonality", "ic"),
        metrics={"rank_ic": 0.001},
    )
    assert ff.failure_modes == ("ic", "orthogonality")


def test_failed_candidate_rejects_infinite_metric() -> None:
    with pytest.raises(ValidationError):
        FailedCandidateSummary(
            name="X",
            cycle_id="cycle-A",
            stage="default",
            decision="FAIL",
            failure_modes=("ic",),
            metrics={"rank_ic": float("inf")},
        )


def test_feedback_bundle_happy_path_markdown() -> None:
    bundle = FeedbackBundle(
        generated_at=_ts(),
        cycles_included=("cycle-A", "cycle-B"),
        window_max_cycles=8,
        active_factors=(_active(),),
        retired_factors=(_retired(),),
        recent_fails=(
            _failed("VolRev_10D", "cycle-A"),
            _failed("VolTwist_20D", "cycle-B"),
        ),
        failure_family_counts={"volume_price_reversal": 2},
        discouraged_families=("volume_price_reversal",),
        notes="generated by pytest",
    )
    md = bundle.to_markdown()

    assert "generated_at" in md
    assert "QualPersist_60D" in md
    assert "VolRet_5D" in md
    assert "VolRev_10D" in md
    assert "volume_price_reversal" in md
    assert "rank_ic=0.004" in md
    assert "Discouraged" in md
    assert "Interpretation rules for LLM" in md


def test_feedback_bundle_enforces_cycles_window() -> None:
    with pytest.raises(ValidationError):
        FeedbackBundle(
            generated_at=_ts(),
            cycles_included=("c1", "c2", "c3"),
            window_max_cycles=2,  # 超过 window 应报错
            active_factors=(),
            retired_factors=(),
            recent_fails=(),
        )


def test_feedback_bundle_rejects_orphan_fail_cycle() -> None:
    with pytest.raises(ValidationError):
        FeedbackBundle(
            generated_at=_ts(),
            cycles_included=("cycle-A",),
            window_max_cycles=8,
            active_factors=(),
            retired_factors=(),
            recent_fails=(_failed("X", "cycle-NOT-IN-LIST"),),
        )


def test_feedback_bundle_markdown_omits_empty_sections() -> None:
    bundle = FeedbackBundle(
        generated_at=_ts(),
        cycles_included=(),
        window_max_cycles=8,
    )
    md = bundle.to_markdown()
    # 没有任何数据时各分区标题都不应出现，避免给 LLM 制造"空等于没有限制"的错觉
    assert "L3 active factors" not in md
    assert "retired factors" not in md
    assert "Recent L2 failures" not in md
    assert "Discouraged families" not in md
    # 但 Interpretation 必须始终在，保证 prompt 形状稳定
    assert "Interpretation rules for LLM" in md
