"""
根据当前 data 配置生成「因子组消融」实验规格，供 scripts/run_tuning_experiments.py 批量调用 run_train.py。

示例：
  python scripts/run_feature_ablation.py --pipeline config/pipeline.yaml --out data/tuning/specs/generated_feature_ablation.yaml
  python scripts/run_tuning_experiments.py --spec data/tuning/specs/generated_feature_ablation.yaml --runs-dir data/tuning/runs_ablation --max-experiments 3
  python scripts/collect_tuning_results.py --runs-dir data/tuning/runs_ablation --out-dir data/tuning/summary
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Any, Dict, List

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _slug(name: str) -> str:
    s = re.sub(r"[^\w\-]+", "_", name.strip())
    return re.sub(r"_+", "_", s).strip("_") or "set"


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="生成因子组消融 tuning 规格 YAML")
    p.add_argument("--pipeline", type=str, default="config/pipeline.yaml", help="pipeline 配置（用于定位 data 配置路径）")
    p.add_argument(
        "--data-config",
        type=str,
        default=None,
        help="直接指定 data yaml；默认从 pipeline 的 data_config 读取",
    )
    p.add_argument(
        "--sets",
        type=str,
        default=None,
        help="逗号分隔的 feature set 名列表；默认使用 data.yaml 中的 active_feature_sets",
    )
    p.add_argument(
        "--modes",
        type=str,
        default="full,drop_one",
        help="full=全量基准; drop_one=每次去掉一组; single=每次只保留一组。逗号分隔",
    )
    p.add_argument("--model-type", type=str, choices=["lgb", "gru"], default="lgb", help="消融使用的单模型类型（与 run_tuning_experiments 一致）")
    p.add_argument("--prefix", type=str, default="ablation", help="experiment_id 前缀")
    p.add_argument("--out", type=str, default="data/tuning/specs/generated_feature_ablation.yaml", help="输出的 spec 路径")
    return p.parse_args()


def load_yaml(path: Path) -> Dict[str, Any]:
    import yaml  # type: ignore

    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def main() -> None:
    args = parse_args()
    os.chdir(PROJECT_ROOT)

    pipeline_path = (PROJECT_ROOT / args.pipeline).resolve()
    pipe = load_yaml(pipeline_path)
    data_path = (PROJECT_ROOT / args.data_config).resolve() if args.data_config else (PROJECT_ROOT / pipe["data_config"]).resolve()
    data_cfg = load_yaml(data_path)

    if args.sets:
        base_sets = [s.strip() for s in args.sets.split(",") if s.strip()]
    else:
        base_sets = list((data_cfg.get("data") or {}).get("active_feature_sets") or [])

    if not base_sets:
        raise ValueError("未找到 active_feature_sets：请在 data.yaml 中配置或使用 --sets")

    modes = [m.strip() for m in args.modes.split(",") if m.strip()]
    valid_modes = {"full", "drop_one", "single"}
    for m in modes:
        if m not in valid_modes:
            raise ValueError(f"未知 mode: {m}，允许: {sorted(valid_modes)}")

    experiments: List[Dict[str, Any]] = []
    mt = args.model_type

    if "full" in modes:
        eid = f"{args.prefix}_{mt}_full"
        experiments.append(
            {
                "experiment_id": eid,
                "model_type": mt,
                "notes": f"因子组全量基准 ({len(base_sets)} 组)",
                "data_overrides": {"data.active_feature_sets": list(base_sets)},
            }
        )

    if "drop_one" in modes:
        for s in base_sets:
            subset = [x for x in base_sets if x != s]
            if not subset:
                continue
            eid = f"{args.prefix}_{mt}_drop_{_slug(s)}"
            experiments.append(
                {
                    "experiment_id": eid,
                    "model_type": mt,
                    "notes": f"去掉因子组: {s}（剩余 {len(subset)} 组）",
                    "data_overrides": {"data.active_feature_sets": subset},
                }
            )

    if "single" in modes:
        for s in base_sets:
            eid = f"{args.prefix}_{mt}_only_{_slug(s)}"
            experiments.append(
                {
                    "experiment_id": eid,
                    "model_type": mt,
                    "notes": f"仅保留因子组: {s}",
                    "data_overrides": {"data.active_feature_sets": [s]},
                }
            )

    spec: Dict[str, Any] = {
        "version": 1,
        "defaults": {
            "base_pipeline_config": str(pipeline_path.relative_to(PROJECT_ROOT)).replace("\\", "/"),
            "selection_metric": "ic_qlib_ensemble_icir",
            "min_selection_score": 0.0,
            "min_valid_windows": 3,
            "notes": "generated by scripts/run_feature_ablation.py",
        },
        "experiments": experiments,
    }

    out_path = (PROJECT_ROOT / args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    import yaml  # type: ignore

    with open(out_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(spec, f, allow_unicode=True, sort_keys=False)

    print(f"已写入 {out_path} ，共 {len(experiments)} 个实验。")
    print("下一步: python scripts/run_tuning_experiments.py --spec " + str(out_path.relative_to(PROJECT_ROOT)).replace("\\", "/"))


if __name__ == "__main__":
    main()
